[project]
name = "mortgage-dash"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dash>=3.2.0",
    "flask>=3.1.1",
    "pandas>=2.3.1",
    "requests>=2.32.4",
    "ruff>=0.12.8",
    "flask-cors", 
]
